/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.chophi.learnjava;

import java.util.Random;
import java.util.stream.Stream;

import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.NonNull;

@RequiredArgsConstructor(staticName = "of")
@AllArgsConstructor(access = AccessLevel.PROTECTED)
class ConstructorExample<T> {
    private int x, y;
    @NonNull private T description;
    @NonNull private Integer value;

    @NoArgsConstructor
    public static class NoArgsExample {
        @NonNull private String field;
    }
}

public class TryLombok {
    public static void main(String[] args) {
    }
}
