/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.chophi.learnjava;

import java.util.Random;
import java.util.stream.Stream;

public class TryStream {
    public static void main(String[] args) {
        final Random rand = extracted();
        Stream<Integer> stream = Stream.generate(() -> rand.nextInt() % 10);
        stream.limit(10).forEach(System.out::println);
        System.out.println("This is inside TryStream");
    }

    private static Random extracted() {
        final Random rand = new Random();
        return rand;
    }

}
