use learnsql
CREATE TABLE EMPLOYEE_TBL (
EMP_ID       CHAR(9)      NOT NULL,
EMP_NAME     VARCHAR(40)  NOT NULL,
EMP_ST_ADDR  VARCHAR(20)  NOT NULL,
EMP_CITY     VARCHAR(15)  NOT NULL,
EMP_ST       CHAR(2)      NOT NULL,
EMP_ZIP      INTEGER(5)   NOT NULL,
EMP_PHONE    INTEGER(10)  NULL,
EMP_PAGER    INTEGER(10)  NULL
);
